### ISSUE TITLE
The SimpleSAML_Auth_Simple is now using namespaces.

### ISSUE THREAD

**Issue by Vinq-it-JV** [hslavich/SimplesamlphpBundle#21]
Hi There,

Just noticed a warning:

_The class or interface 'SimpleSAML_Auth_Simple' is now using namespaces, please use 'SimpleSAML\Auth\Simple'._

So I changed the services.yml to: 

```
services:
    simplesamlphp.auth:
        class: SimpleSAML\Auth\Simple #SimpleSAML_Auth_Simple
        arguments: [ '%simplesamlphp.sp%' ]
```

Can you please take this into account on the next update?

Cheers,

Jeroen (pronounced: jer-oon) ;-)
